### ISSUE TITLE
Pizza Margherita

### ISSUE THREAD

**Issue by ibias666** [AbuSpace/pizza#15]
Como **Amante de Pizza** Desejo **Cadastrar os passos desta pizza** Para **que todos possam seguir a minha receita**

**Critérios de Aceite** 
   - Molho de tomate fresco
   - Mussarela de búfala
   - Tomates cereja cortados ao meio
   - Folhas de manjericão fresco
   - Um fio de azeite de oliva extra virgem

**Comment by LeMalk** [comment]
- [] Colocar foto ilustrativa
 - [] Colocar passo a passo de como rechear
**Como Testar:**
- [] Chamar o link do título da pizza e ver se os dados são apresentados
