### ISSUE TITLE
Pizza Pepperoni

### ISSUE THREAD

**Issue by Gabrielarcenio** [AbuSpace/pizza#35]
Como **\<Ator\>** Desejo **\<Funcionalidade\>** Para **\<Valor\>**

**Critérios de Aceite**
1 Bola de Pizza
Molho de Tomate
Mussarela
Manjericão
Tomates
Azeite
Temperos a Gosto

**Comment by abuzitos** [comment]
- [ ] Tick 01
- [ ] Tick 02
- [ ] Tick 03
